import { Activity, Bot, ShieldCheck, TrendingUp, Wallet, Zap } from "lucide-react";
const pairs=["EURUSD","GBPUSD","USDJPY","XAUUSD","Volatility 75","Boom 500","Crash 500"];
export default function Home(){return <main><header><div><span className="eyebrow">ORACLE TRADING ENGINE</span><h1>Market intelligence. Controlled execution.</h1><p>Forex + Deriv synthetic trading with signal scoring, risk controls and broker execution.</p></div><button className="live">PAPER MODE</button></header>
<section className="grid stats"><Card icon={<Wallet/>} title="Equity" value="$10,000.00" meta="+0.00% today"/><Card icon={<TrendingUp/>} title="Open P/L" value="$0.00" meta="0 positions"/><Card icon={<ShieldCheck/>} title="Risk" value="1.0%" meta="per trade"/><Card icon={<Activity/>} title="Engine" value="STANDBY" meta="awaiting market data"/></section>
<section className="panel"><div className="panelHead"><div><span className="eyebrow">MARKET ENGINE</span><h2>Instrument selection</h2></div><button className="primary"><Zap size={16}/> Run analysis</button></div><div className="pairs">{pairs.map((p,i)=><button className={i<4?"pair active":"pair"} key={p}>{p}<span>{i<4?"ON":"OFF"}</span></button>)}</div></section>
<section className="grid lower"><div className="panel"><div className="panelHead"><h2>Oracle decision matrix</h2><span className="muted">No live orders</span></div><div className="signals"><Signal pair="EURUSD" score="78" bias="BUY" reason="Trend + structure + momentum"/><Signal pair="GBPUSD" score="64" bias="WAIT" reason="Resistance conflict"/><Signal pair="USDJPY" score="81" bias="BUY" reason="Multi-timeframe confluence"/><Signal pair="XAUUSD" score="42" bias="WAIT" reason="Volatility regime unstable"/></div></div>
<div className="panel"><div className="panelHead"><h2>Safety controls</h2></div><ul className="checks"><li><ShieldCheck/> Stop-loss required</li><li><ShieldCheck/> Break-even protection</li><li><ShieldCheck/> Daily loss limit</li><li><ShieldCheck/> Max exposure cap</li><li><ShieldCheck/> Emergency trading halt</li></ul></div></section>
<section className="panel"><div className="panelHead"><div><span className="eyebrow">CONNECTIONS</span><h2>Broker accounts</h2></div><button className="secondary">Connect broker</button></div><div className="broker"><div><b>MetaTrader 5</b><small>Execution bridge: not connected</small></div><span className="dot"></span></div><div className="broker"><div><b>Deriv</b><small>WebSocket: public market data only</small></div><span className="dot"></span></div><p className="notice">Credentials are never placed in the browser. Production connections use encrypted server-side secrets and an execution bridge.</p></div>
<footer>Oracle Trading Engine · Paper-first architecture · Trading involves substantial risk.</footer></main>}
function Card({icon,title,value,meta}:{icon:React.ReactNode,title:string,value:string,meta:string}){return <div className="card">{icon}<span>{title}</span><strong>{value}</strong><small>{meta}</small></div>}
function Signal({pair,score,bias,reason}:{pair:string,score:string,bias:string,reason:string}){return <div className="signal"><div><b>{pair}</b><small>{reason}</small></div><strong>{score}%</strong><span className={bias==="BUY"?"buy":"wait"}>{bias}</span></div>}